pipeline {
	agent any
	stages{
		stage('Build') {
			steps{
				echo "Build"
			}
		}

		stage('Test') {
			steps{
				echo "Test"
			}
		}

		stage('Integration Test') {
			steps{
				echo "Integration Test"
			}
		}
	}
	post{
		always{
			echo "Im awesome. I run always."
		}
		success{
			echo "I run when you are successful."
			mail bcc: '', body: 'This message was sent from Jenkins.', cc: '', from: '', replyTo: '', subject: 'Jenkins Pipeline', to: 'yasser.fereidouni@gmail.com'
		}
		failure{
			echo "I run when you fail"
		}
	}
}
